### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by k9lego** [Yahweasel/craig#1]
Hello,
Any chance you could add a License to this project? GNUv3 is pretty popular, or MIT if you are feeling generous.

**Comment by Yahweasel** [comment]
You mean such as the license text in the header of every source file?

**Comment by k9lego** [comment]
Ah gotcha. I'm used to it being a LICENSE.md file at the root of the project, so I just assumed you didn't have one. Sorry about that, thanks for the quick response!
