### ISSUE TITLE
1 track is slow, other tracks are good

### ISSUE THREAD

**Issue by HappyClem** [Yahweasel/craig#11]
Hello,

My friends have recorded a discussion. There was 5 tracks.
In 1 of the tracks, the voice was slowed-down. We tried to sped it up in post but no try could match either the original voice speed nor the tempo of the conversation.
We are planning to try another discussion like this soon to this if this happens again.

We are all using windows 10, windows discord client and there was no connection drop or noticeable lag during the call.
We used a music bot and his track was also recorded without problems.

Any idea why this happens and how we can prevent this ?

**Comment by Yahweasel** [comment]
Hi,

Slowdown is Craig's equivalent of robotting. Craig receives partial audio, and in an attempt to sync the audio and make it fit into the time it was _supposed_ to fill, he stretches it. If you extracted the raw audio, you'd find that probably a lot of it was missing.

Unfortunately, Discord treats bots as second-class citizens, and tends to give much less reliable streams to bots than to users, so there is nothing that can be done to prevent this. This and similar Discord problems is why I wrote the associated web app, through which you can bypass Discord and so record without Discord's interference.

You may want to try a different voice server ("voice region"), particularly if you're on the perennially-overloaded US East. Other than that, the only solution is to bypass Discord.

**Comment by HappyClem** [comment]
Hi, sorry to come back to this.
We did an other recording with the same parameters and 2 new people.
All tracks are good EXCEPT for the same person as last time. Her tracks his slowed down but stretched enough to be where it should.  It is the same user.
Maybe it is special caracters in her name so maybe it is that (When download, i found there file name contain a lot "_".
Because it is only that users, I don't think it is lag from the bot anymore.
If you need more infos, ask me no problem.
