### ISSUE TITLE
Won't join any Voice Channel

### ISSUE THREAD

**Issue by Kr4u7** [Yahweasel/craig#3]
Hi @Yahweasel ,

### Problem:
Craig won't join any Voice channels, while cycling through these three error messages:

`:craig: <(Failed to join! If I persistently fail to join, it may be an issue with the voice server. Try changing the server region in server settings. TypeError: Cannot read property 'send' of undefined)`

`:craig: <(Failed to join! If I persistently fail to join, it may be an issue with the voice server. Try changing the server region in server settings. Error: Disconnected)`

`:craig: <(Failed to join! If I persistently fail to join, it may be an issue with the voice server. Try changing the server region in server settings. Error: Voice connection timeout)`

### steps to reproduce:
**On our specific server:**

- issue `:craig:, join` or `:craig:, join VOICECHANNEL`
- craig changes sometimes name to [recording]craig
- error

**on other test servers:**
not reproducible

### what we tried to solve it:

- change location of the server multiple times

thank you for your awesome bot, and hopefully good advice on why this won't work or what we can do :)

**Comment by Kr4u7** [comment]
My first impulse thought on this was that there are too many members on that server (>2000) and the fetchAllMember function takes too long.

**Comment by Yahweasel** [comment]
This is not the appropriate forum for this sort of help request. Craig has a support server.
