### ISSUE TITLE
Audio output is a BIG FAIL

### ISSUE THREAD

**Issue by wstd1234** [Yahweasel/craig#4]
Audio output is a BIG FAIL.

https://drive.google.com/file/d/1rcdra66ig3ed7UETy7JjD6mFhhYWMqWy/view?usp=sharing

One of the voice output turned "chipmunk". The real voice was never like this.

You can "educate" people with an "audio primer" all you want but it's all useless if it FAILS BIG TIME.

Downloaded FLAC, AAC, Audacity, raw ogg versions and still all failed miserably. The raw ogg file completely fails to open.

Just make a super simple "all-voices-in-1" (((MP3 MP3 MP3))) download link and all the problems would've been magically solved.

So what if it's obsolete, if it's 100% reliable for normal users? Why impose an audio enthusiast's superiority upon normal users? So what if it's taking space during silence, if the end file is 10x smaller in size compared with "modern" audio formats?

And oh, that "ennuicastr" either takes forever to load or fails to load at all, making it totally useless in the first place.

MP3/MPEG-1 can never deliver the same quality as AAC, simply because MP3/MPEG-1 is proven, by this rotten file, to be BETTER THAN AAC & ETC.

MP3/MPEG-1 is not the file format YOUR software wants. MP3/MPEG-1 is the file format that EVERYBODY ELSE'S software wants.

Why be willing to adapt or stand under an INFERIOR & BLOATED "modern" audio format, when OBSOLETE TECH WORKS JUST FINE & PERFECTLY?

**Comment by Yahweasel** [comment]
github's issues board is not a venue for drivel.
