### ISSUE TITLE
Bit rot in the readme links.

### ISSUE THREAD

**Issue by ryantheleach** [Yahweasel/craig#5]
Both 

EnnuiCastr ( https://bitbucket.org/Yahweasel/ennuicastr/ ) 
Ennuizel ( https://bitbucket.org/Yahweasel/ennuizel/ ) 

Are linking to incorrect repo's. You will know where the best place to link to will be, but for others interested before this is fixed, I found them here.

https://github.com/Yahweasel/ennuizel
https://ecastr.com/

**Comment by Yahweasel** [comment]
Thanks! Fixed in a6eb00477f205a27ba10900e976ad54c05b5de9e.
