### ISSUE TITLE
Record video stream in addition to audio

### ISSUE THREAD

**Issue by KuraFire** [Yahweasel/craig#6]
This may not be possible per current Discord features/APIs, and this may be super complicated work given that Discord does multiple video streams and Craig would basically have to either be tied in with a manual controller (to decide, say, which screen share stream to watch and record when there are two). But…

It would be amazing if Craig could record *some* kind of video feed as well, to make uploads to YouTube much more interesting content.

**Comment by KuraFire** [comment]
Context: we use Craig for our public [SourceCred](https://github.com/sourcecred) calls, and are exploring bringing those to YouTube. An audio-only version would not be ideal, and a screen recording would be fully manual work for someone.

**Comment by Yahweasel** [comment]
Discord bots are not privy to video streams. You may be interested in https://ecastr.com/ . I may eventually fold video recording from that project back into Ennuicastr as built into Craig, but not soon.
