### ISSUE TITLE
Support for Docker container

### ISSUE THREAD

**Issue by MatteoGheza** [Yahweasel/craig#7]
I'm trying to install craig on a Ubuntu vps, but, after installing everything following README.md, the bot don't work.
Can you add a Dockerfile for running this into Docker?

**Comment by Yahweasel** [comment]
A user has written detailed instructions in the wiki. Perhaps they will work better, but I haven't looked at them. Another thing I've never looked at is Docker. I'm not going to learn Docker just to write a Dockerfile for Craig. If you want to write your own Dockerfile and submit a PR, I'll look at it.

**Comment by OmnesPotens** [comment]
@SMarioMan I see that #224 implements this and has feedback requesting a proper `docker-compose.yml` to be included along with it. Any chance we can get that in and merge the PR?

**Comment by SMarioMan** [comment]
> [@SMarioMan](https://github.com/SMarioMan) I see that [#224](https://github.com/CraigChat/craig/pull/224) implements this and has feedback requesting a proper `docker-compose.yml` to be included along with it. Any chance we can get that in and merge the PR?

Thanks for bumping this. I just addressed the feedback and requested a re-review.
