### ISSUE TITLE
Should I integrate my weird "local-only" version?

### ISSUE THREAD

**Issue by za3k** [Yahweasel/craig#9]
I'd like to offer a version of Craig that _is_ easy to run yourself, mostly by cutting dependencies. To me, it seems that if you're running your own version of Craig, you probably don't need the website--I would offer a version that just saves audio files locally, eliminating PHP, and does any post-processing with (actual) ffmpeg or CLI tools, eliminating js dependencies.

Now one thing I could do is fork and delete several components of the code--if that's what you prefer, just ignore this. But if you'd like, I can also try to integrate the "local-only" version behind a command-line flag, and add a patch and user guide. Up to you.

**Comment by Yahweasel** [comment]
How big of a change are we talking about? I don't want to long-term maintain something huge and complicated, but if it's just a few corners not likely to break, that seems helpful.

**Comment by za3k** [comment]
I think it'll probably just be a few if statements to "comment out" code, but I'll re-open when/if I have an actual PR.
